export const PHONE_DATA_REQUEST='PHONE_DATA_REQUEST';
export const PHONE_DATA_SUCCESS='PHONE_DATA_SUCCESS';
export const PHONE_DATA_FAILURE='PHONE_DATA_FAILURE';

export const LAPTOP_DATA_REQUEST='LAPTOP_DATA_REQUEST';
export const LAPTOP_DATA_SUCCESS='LAPTOP_DATA_SUCCESS';
export const LAPTOP_DATA_FAILURE='LAPTOP_DATA_FAILURE';

export const TV_DATA_REQUEST='TV_DATA_REQUEST';
export const TV_DATA_SUCCESS='TV_DATA_SUCCESS';
export const TV_DATA_FAILURE='TV_DATA_FAILURE';

export const ADD_PRODUCT_CART_REQUEST='ADD_PRODUCT_CART_REQUEST';
export const ADD_PRODUCT_CART_SUCCESS='ADD_PRODUCT_CART_SUCCESS';
export const ADD_PRODUCT_CART_FAILURE='ADD_PRODUCT_CART_FAILURE';

export const GET_PRODUCT_CART_REQUEST='GET_PRODUCT_CART_REQUEST';
export const GET_PRODUCT_CART_SUCCESS='GET_PRODUCT_CART_SUCCESS';
export const GET_PRODUCT_CART_FAILURE='GET_PRODUCT_CART_FAILURE';




